- name: Ensure APT cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common CLI packages
  apt:
    name:
      - git
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

