services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    entrypoint: 
      - "bash"
      - "/home/wait-for-it"
      - "db:5432"
      - "--"
      - "java"
      - "-jar"
      - "/home/tracker.jar"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"       # Graphite web UI
      - "2003:2003"   # Carbon plaintext
      - "2004:2004"   # Carbon pickle
      - "8125:8125/udp" # StatsD
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - graphite
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  pgdata:
  grafana-storage:
