- name: Ensure APT keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Check if Docker GPG key exists
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: docker_gpg_key

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: not docker_gpg_key.stat.exists

- name: Check if Docker APT source file exists
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_repo_file

- name: Add Docker APT repository (signed-by method)
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable
    mode: '0644'
  when: not docker_repo_file.stat.exists

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker and Docker Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add current user to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

